### ISSUE TITLE
Modal lingers when "Stay on ticket" selected

### ISSUE THREAD

**Issue by ilovelofi** [zendesklabs/oops_app#9]
If you select "Stay on ticket" upon submission, the modal does not disappear after the timer is up. It only disappears when "Close tab" or "Next ticket in view" are selected.

**Comment by dpawluk** [comment]
@ilovelofi I just merged a new commit. Would you mind testing and letting me know if this still happens?

**Comment by dpawluk** [comment]
just tested live too, without this error. I'll close it for now cause I like to clean things :D
